apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newsgradient-analize
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: newsgradient-analize
    newName: rg.fr-par.scw.cloud/djnd/newsgradient-analize
    newTag: 'ec1c2b106f71a88f7c8103d64f12afe64b33e15e'