apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newsgradient-analize
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
images:
  - name: newsgradient-analize
    newName: rg.fr-par.scw.cloud/djnd/newsgradient-analize
    newTag: '465f80f350990ea347c4384fe732c8c58bb11775'