apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: newsgradient-analize-pvc
  labels:
    app: newsgradient-analize
  # annotations:
  #   pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: 'scw-bssd-retain'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi