version: '3'

services:
  flask:
    build: ./api
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    environment:
      APP_ENV: production
    entrypoint: ./run.sh
    # command: flask run --host=0.0.0.0